import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";

const CHECK = join(
  resolve(dirname(fileURLToPath(import.meta.url)), ".."),
  "scripts",
  "tp-attribution.mjs",
);

function check(text) {
  const result = spawnSync(process.execPath, [CHECK], { input: text, encoding: "utf8" });
  return { rejected: result.status === 1, stderr: result.stderr };
}

describe("the attribution check", () => {
  const CREDITS = [
    "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
    "Generated with Claude Code",
    "Generated by Claude",
    "This file is AI-generated.",
    "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>",
    "co-authored-by: some copilot <x@y.z>",
    "Written by an AI.",
    "AI-assisted refactor.",
  ];

  for (const text of CREDITS) {
    it(`rejects: ${text.slice(0, 48)}`, () => {
      assert.equal(check(text).rejected, true, text);
    });
  }

  // Everything here names a model without crediting it for the work, and a
  // check that could not tell the difference would be switched off within a
  // week — which is worse than no check. `.claude/` alone names Claude on
  // nearly every line.
  const MENTIONS = [
    "Gemini is a bulk reader that is allowed to be absent.",
    "Claude is authoritative. Router output is not repository evidence.",
    "gemini-3.8-flash supports low, medium and high.",
    "The deny reason reaches Claude, which is why this design is possible.",
    "Co-authored-by: Raishark <raivel.studio@gmail.com>",
    "x-goog-api-key, never in the URL. See ai-policy.md.",
    "feat(db): the application connects as a role that owns nothing",
  ];

  for (const text of MENTIONS) {
    it(`allows: ${text.slice(0, 48)}`, () => {
      assert.equal(check(text).rejected, false, text);
    });
  }

  it("names the line and the rule, so the fix is obvious", () => {
    const { rejected, stderr } = check(
      "A real body.\n\n🤖 Generated with [Claude Code](https://x)\n",
    );

    assert.equal(rejected, true);
    assert.match(stderr, /line 3/);
    assert.match(stderr, /robot-credit/);
    // And says what is still allowed, so nobody switches the check off to get
    // a legitimate sentence past it.
    assert.match(stderr, /as a dependency, in documentation or/);
  });

  it("passes clean text with nothing to say", () => {
    const { rejected, stderr } = check(
      "fix(db): the guard could not see a function it had to protect\n",
    );

    assert.equal(rejected, false);
    assert.equal(stderr, "");
  });

  it("reads the last commit when asked", () => {
    // The mode that matters: a trailer added by tooling is not visible in the
    // subject line, and `%(trailers)` is where it hides.
    const result = spawnSync(process.execPath, [CHECK, "--commit"], { encoding: "utf8" });

    assert.equal(result.status, 0, result.stderr);
  });
});
